src/Web/AspNetCoreTemplate.Web/Controllers/AreasController.cs
namespace AspNetCoreTemplate.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using AspNetCoreTemplate.Common;
    using AspNetCoreTemplate.Services.Data.Addresses;
    using AspNetCoreTemplate.Web.ViewModels.Areas;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class AreasController : Controller
    {
        private readonly IAreasService areasService;
        private readonly ICitiesService citiesService;

        public AreasController(
            IAreasService areasService,
            ICitiesService citiesService)
        {
            this.areasService = areasService;
            this.citiesService = citiesService;
        }

        [Authorize]
        public IActionResult Create()
        {
            var cities = this.citiesService.GetAllCities<CityDropDownViewModels>();

            var viewModel = new AreaCreateInputModel
            {
                Cities = cities,
            };
            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(AreaCreateInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var areaId = await this.areasService.CreateAsyncArea(input.AreaName.ToString(), input.CityId, input.Image);
            this.TempData["InfoMessageAreas"] = "Area was created!";
            return this.RedirectToAction(nameof(this.All));
        }

        [Authorize]
        [Authorize(Roles = "Administrator, Admin")]
        public async Task<IActionResult> CreateAllAreaInSofia()
        {
            var cities = this.citiesService.GetAllCities<CityDropDownViewModels>();
            var cityId = string.Empty;

            foreach (var city in cities)
            {
                if (city.CityName == "SOFIA")
                {
                    cityId = city.Id;
                }
            }

            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction(nameof(this.All));
            }

            var areas = this.Image();

            for (int i = 0; i < areas.Count; i++)
            {
                string image = areas[i + 1][0];
                string areaName = areas[i + 1][1];
                var area = await this.areasService.CreateAsyncArea(areaName, cityId, image);
            }

            this.TempData["InfoMessageAreas"] = "Areas Sofia was created!";
            return this.RedirectToAction(nameof(this.All));
        }

        [Authorize]
        public IActionResult All(AreasByCity input)
        {
            var viewModel = new ViewModels.Areas.AreaIndexViewModel();

            var areas = this.areasService.GetAllAreas<AreasAll>(input.Id);

            viewModel.Areas = areas;

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult NavBar()
        {
            return this.View();
        }

        private Dictionary<int, List<string>> Image()
        {
            var images = new Dictionary<int, List<string>>();
            images.Add(1, new List<string> { AllImage.Sredec, "Sredec" });
            images.Add(2, new List<string> { AllImage.KrasnoSelo, "KrasnoSelo" });
            images.Add(3, new List<string> { AllImage.Vazrajdane, "Vazrajdane" });
            images.Add(4, new List<string> { AllImage.Oborishte, "Oborishte" });
            images.Add(5, new List<string> { AllImage.Serdika, "Serdika" });
            images.Add(6, new List<string> { AllImage.Poduene, "Poduene" });
            images.Add(7, new List<string> { AllImage.Slatina, "Slatina" });
            images.Add(8, new List<string> { AllImage.Izgrev, "Izgrev" });
            images.Add(9, new List<string> { AllImage.Lozenetz, "Lozenetz" });
            images.Add(10, new List<string> { AllImage.Triadica, "Triadica" });
            images.Add(11, new List<string> { AllImage.KrasnaPolqna, "KrasnaPolqna" });
            images.Add(12, new List<string> { AllImage.Ilinden, "Ilinden" });
            images.Add(13, new List<string> { AllImage.Nadejda, "Nadejda" });
            images.Add(14, new List<string> { AllImage.Iskar, "Iskar" });
            images.Add(15, new List<string> { AllImage.Mladost, "Mladost" });
            images.Add(16, new List<string> { AllImage.Studentski, "Studentski" });
            images.Add(17, new List<string> { AllImage.Vitosha, "Vitosha" });
            images.Add(18, new List<string> { AllImage.OvchaKupel, "OvchaKupel" });
            images.Add(19, new List<string> { AllImage.Lulin, "Lulin" });
            images.Add(20, new List<string> { AllImage.Vrabnica, "Vrabnica" });
            images.Add(21, new List<string> { AllImage.NoviIskar, "NoviIskar" });
            images.Add(22, new List<string> { AllImage.Kremikovci, "Kremikovci" });
            images.Add(23, new List<string> { AllImage.Pancharevo, "Pancharevo" });
            images.Add(24, new List<string> { AllImage.Bankq, "Bankq" });

            return images;
        }
    }
}

src/Web/AspNetCoreTemplate.Web/Controllers/CitiesController.cs
namespace AspNetCoreTemplate.Web.Controllers
{
    using System.Threading.Tasks;

    using AspNetCoreTemplate.Services.Data.Addresses;
    using AspNetCoreTemplate.Web.ViewModels.Cities;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class CitiesController : Controller
    {
        private readonly ICitiesService citiesServices;

        public CitiesController(ICitiesService citiesServices)
        {
            this.citiesServices = citiesServices;
        }

        [Authorize]
        [Authorize(Roles = "Administrator, Admin")]
        public IActionResult Create()
        {
            var viewModel = new CityCreateInputViewModel();

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        [Authorize(Roles = "Administrator, Admin")]
        public async Task<IActionResult> Create(CityCreateInputViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var cityId = await this.citiesServices.CreateAsyncCity(input.CityName);
            this.TempData["InfoMessageCity"] = "City created!";
            return this.RedirectToAction(nameof(this.All));
        }

        [Authorize]
        [Authorize(Roles = "Administrator, Admin")]
        public IActionResult All()
        {
            var viewModel = new ViewModels.Cities.CityIndexViewModel();

            var cities = this.citiesServices.GetAllCities<CitiesAll>();

            viewModel.Cities = cities;

            return this.View(viewModel);
        }

        [Authorize]
        [Authorize(Roles = "Administrator, Admin")]
        public IActionResult NavBar()
        {
            return this.View();
        }
    }
}

src/Web/AspNetCoreTemplate.Web/Controllers/LocationsController.cs
namespace AspNetCoreTemplate.Web.Controllers
{
    using System.Threading.Tasks;

    using AspNetCoreTemplate.Services.Data.Addresses;
    using AspNetCoreTemplate.Web.ViewModels.Locations;
    using AspNetCoreTemplate.Web.ViewModels.Streets;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class LocationsController : Controller
    {
        private readonly IAreasService areasService;
        private readonly ICitiesService citiesService;
        private readonly IStreetsService streetsService;
        private readonly ILocationsService locationsService;

        public LocationsController(
            IAreasService areasService,
            ICitiesService citiesService,
            IStreetsService streetsService,
            ILocationsService locationsService)
        {
            this.areasService = areasService;
            this.citiesService = citiesService;
            this.streetsService = streetsService;
            this.locationsService = locationsService;
        }

        [Authorize]
        public IActionResult Create()
        {
            var viewModel = new CreateLocationsInputModel();

            var cities = this.citiesService.GetAllCities<CitiesDropDownMenuInStreet>();

            viewModel.Cities = cities;

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(CreateLocationsInputModel input)
        {
            var areas = this.areasService.GetAllAreas<AreasDropDownMenu>(input.CityId);
            var viewModel = new CreateLocationsInputModel();
            viewModel.Areas = areas;

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult Create1(CreateLocationsInputModel input)
        {
            var city = this.citiesService.GetById<CitiesDropDownMenuInStreet>(input.CityId);
            var areas = this.areasService.GetAllAreas<AreasDropDownMenu>(input.CityId);
            var viewModel = new CreateLocationsInputModel();
            viewModel.Areas = areas;
            viewModel.CityName = city.CityName;
            viewModel.CityId = input.CityId;

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create2(CreateLocationsInputModel input)
        {
            var city = this.citiesService.GetById<CitiesDropDownMenuInStreet>(input.CityId);
            var area = this.areasService.GetById<AreasDropDownMenu>(input.AreaId);

            var streets = this.streetsService.GetAllStreets<StreetDropDownMenu>(input.AreaId);

            var viewModel = new CreateLocationsInputModel();

            viewModel.AreaName = area.AreaName;
            viewModel.CityName = city.CityName;
            viewModel.Streets = streets;

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create3(CreateLocationsInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var locationId = await this.locationsService.CreateAsyncLocation(input.Apartament, input.Number, input.Flour, input.Entrance, input.StreetId);
            this.TempData["InfoMessageAreas"] = "Location was created!";
            return this.RedirectToAction(nameof(this.NavBar));
        }

        [Authorize]
        public IActionResult NavBar()
        {
            return this.View();
        }
    }
}

src/Web/AspNetCoreTemplate.Web/Controllers/StreetsController.cs
namespace AspNetCoreTemplate.Web.Controllers
{
    using System.Threading.Tasks;

    using AspNetCoreTemplate.Services.Data.Addresses;
    using AspNetCoreTemplate.Web.ViewModels.Streets;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class StreetsController : Controller
    {
        private readonly IAreasService areasService;
        private readonly ICitiesService citiesService;
        private readonly IStreetsService streetsService;

        public StreetsController(
            IAreasService areasService,
            ICitiesService citiesService,
            IStreetsService streetsService)
        {
            this.areasService = areasService;
            this.citiesService = citiesService;
            this.streetsService = streetsService;
        }

        [Authorize]
        public IActionResult Create1()
        {
            var viewModel = new CreateStreetInputModel();

            var cities = this.citiesService.GetAllCities<CitiesDropDownMenuInStreet>();

            viewModel.Cities = cities;

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create1(CreateStreetInputModel input)
        {
            var areas = this.areasService.GetAllAreas<AreasDropDownMenu>(input.CityId);
            var viewModel = new CreateStreetInputModel();
            viewModel.Areas = areas;

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult Create2(CreateStreetInputModel input)
        {
            var city = this.citiesService.GetById<CitiesDropDownMenuInStreet>(input.CityId);
            var areas = this.areasService.GetAllAreas<AreasDropDownMenu>(input.CityId);
            var viewModel = new CreateStreetInputModel();
            viewModel.Areas = areas;
            viewModel.CityName = city.CityName;

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult Create3(string id)
        {
            var city = this.citiesService.GetCityNameByAreaId(id);
            var areas = this.areasService.GetById<AreasDropDownMenu>(id);
            var viewModel = new CreateStreetInputModel();
            viewModel.AreaId = id;
            viewModel.AreaName = areas.AreaName;
            viewModel.CityName = city;

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create3(CreateStreetInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var streetID = await this.streetsService.CreateAsyncStreet(input.Name, input.AreaId);
            this.TempData["InfoMessageAreas"] = "Street was created!";
            return this.RedirectToAction("Create2", "Address", new { id = input.AreaId });
        }

        [Authorize]
        public IActionResult All(StreetByArea input)
        {
            var viewModel = new ViewModels.Streets.StreetIndexViewModel();

            var streets = this.streetsService.GetAllStreets<StreetsAll>(input.Id);

            viewModel.Streets = streets;

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult NavBar()
        {
            return this.View();
        }
    }
}

src/Web/AspNetCoreTemplate.Web/Views/Streets/All.cshtml
@using AspNetCoreTemplate.Common
@using Microsoft.AspNetCore.Mvc.Localization
@using AspNetCoreTemplate.Web.Resources
@inject LocService SharedLocalizer
@inject IViewLocalizer Localizer
@model AspNetCoreTemplate.Web.ViewModels.Streets.StreetIndexViewModel

@{
    this.ViewData["Title"] = $"Welcome to {GlobalConstants.SystemName}";
}

@if (this.TempData["InfoMessageAreas"] != null)
{
    <div class="alert alert-success">
        @this.TempData["InfoMessageAreas"]
    </div>
}

<div class="text-center">
    <h1 class="display-4">@this.ViewData["Title"]</h1>
</div>

@if (Model.Streets.Count() == 0)
{

}
else
{
    <div class="row">
        @foreach (var street in Model.Streets)
        {
            <div class="media col-md-4">
                <div class="media-body">
                    <h5 class="mt-0"><a asp-controller="Streets" asp-action="All" asp-route-id="@street.Id">@street.Name - @SharedLocalizer.GetLocalizedHtmlString("LocationsInThisStreet") (@street.LocatationCount)</a></h5>
                </div>
            </div>
        }
    </div>
}

<hr />
<div>
    <a class="btn btn-primary" asp-area="" asp-controller="Locations" asp-action="Create">@SharedLocalizer.GetLocalizedHtmlString("CreateNewLocation")</a>
    <a class="btn btn-primary" asp-area="" asp-controller="Streets" asp-action="Create1">@SharedLocalizer.GetLocalizedHtmlString("CreateNewStreet")</a>
    <a class="btn btn-primary" asp-area="" asp-controller="Cities" asp-action="All">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>
</div>

src/Web/AspNetCoreTemplate.Web/Views/Streets/AllCity.cshtml
@using AspNetCoreTemplate.Common
@using Microsoft.AspNetCore.Mvc.Localization
@using AspNetCoreTemplate.Web.Resources
@inject LocService SharedLocalizer
@inject IViewLocalizer Localizer
@model AspNetCoreTemplate.Web.ViewModels.Cities.CityIndexViewModel

@{
    this.ViewData["Title"] = $"Welcome to {GlobalConstants.SystemName}";
}

<div class="text-center">
    <h1 class="display-4">@this.ViewData["Title"]</h1>
</div>

@if (Model.Cities.Count() == 0)
{

}
else
{
    <div class="row">
        @foreach (var city in Model.Cities)
        {
            <div class="media col-md-4">
                <div class="media-body">
                    <h5 class="mt-0"><a asp-controller="Areas" asp-action="All" asp-route-id="@city.Id">@city.CityName (@city.AreasCount)</a></h5>
                </div>
            </div>
        }
    </div>
}

<div>
    <a class="btn btn-primary" asp-area="" asp-controller="Areas" asp-action="All">@SharedLocalizer.GetLocalizedHtmlString("CreateNewArea")</a>
    <a class="btn btn-primary" asp-area="" asp-controller="Cities" asp-action="NavBar">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>
</div>

src/Web/AspNetCoreTemplate.Web/Views/Streets/Create1.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using AspNetCoreTemplate.Web.Resources
@inject LocService SharedLocalizer
@inject IViewLocalizer Localizer
@model AspNetCoreTemplate.Web.ViewModels.Streets.CreateStreetInputModel
@{
    this.ViewData["Title"] = "Street Create";
    var cities = Model.Cities.Select(x => new SelectListItem(x.CityName, x.Id.ToString()));
}

<h1>@this.ViewData["Title"]</h1>

<form method="post" asp-action="Create2">
    <div>
        <label asp-for="CityId"></label>
        <select asp-for="CityId" asp-items="cities" class="form-control"></select>
        <span asp-validation-for="CityId" class="text-danger"></span>
    </div>
    <hr />
    <input type="submit" class="btn btn-primary" />
</form>
<a class="btn btn-primary" asp-area="" asp-controller="Streets" asp-action="Create">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>
<a class="btn btn-primary" asp-area="" asp-controller="Areas" asp-action="All">@SharedLocalizer.GetLocalizedHtmlString("All") @SharedLocalizer.GetLocalizedHtmlString("Area")</a>

src/Web/AspNetCoreTemplate.Web/Views/Streets/Create2.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using AspNetCoreTemplate.Web.Resources
@inject LocService SharedLocalizer
@inject IViewLocalizer Localizer
@model AspNetCoreTemplate.Web.ViewModels.Streets.CreateStreetInputModel
@{
    this.ViewData["Title"] = "Street Create";
    var areas = Model.Areas.Select(x => new SelectListItem(x.AreaName, x.Id.ToString()));
    var cityName = Model.CityName.ToString();
}

<h1>@this.ViewData["Title"]</h1>

<form method="post" asp-action="Create3">
    <div class="media-body">
        <h5 class="mt-0">@cityName</h5>
    </div>
    <div>
        <label asp-for="AreaId"></label>
        <select asp-for="AreaId" asp-items="areas" class="form-control"></select>
        <span asp-validation-for="AreaId" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <hr />
    <input type="submit" class="btn btn-primary" />
</form>
<a class="btn btn-primary" asp-area="" asp-controller="Streets" asp-action="Create">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>
<a class="btn btn-primary" asp-area="" asp-controller="Areas" asp-action="All">@SharedLocalizer.GetLocalizedHtmlString("All") @SharedLocalizer.GetLocalizedHtmlString("Area")</a>

src/Web/AspNetCoreTemplate.Web/Views/Streets/Create3.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using AspNetCoreTemplate.Web.Resources
@inject LocService SharedLocalizer
@inject IViewLocalizer Localizer
@model AspNetCoreTemplate.Web.ViewModels.Streets.CreateStreetInputModel
@{
    this.ViewData["Title"] = "Street Create";
}

<h1>@this.ViewData["Title"]</h1>

<form method="post" asp-action="Create3">
    <div class="media-body">
        <h5 class="mt-0">@Model.CityName</h5>
    </div>
    <div class="media-body">
        <h5 class="mt-0">@Model.AreaName</h5>
    </div>
    <div>
        <input type="hidden" asp-for="AreaId" class="form-control" value="@Model.AreaId" />
        <span asp-validation-for="AreaId" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <hr />
    <input type="submit" class="btn btn-primary" />
    <a class="btn btn-primary" asp-area="" asp-controller="Home" asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>
    <a class="btn btn-primary" asp-area="" asp-controller="Areas" asp-action="All">@SharedLocalizer.GetLocalizedHtmlString("All") @SharedLocalizer.GetLocalizedHtmlString("Area")</a>
</form>

src/Web/AspNetCoreTemplate.Web/Views/Streets/NavBar.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using AspNetCoreTemplate.Web.Resources
@inject LocService SharedLocalizer
@inject IViewLocalizer Localizer
@{
    this.ViewData["Title"] = "Street Panel";
}
<ul>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Streets" asp-action="Create1">@SharedLocalizer.GetLocalizedHtmlString("Create")</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="All">@SharedLocalizer.GetLocalizedHtmlString("All")</a>
    </li>
</ul>

<a class="btn btn-primary" asp-area="" asp-controller="Address" asp-action="NavBarAddress">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>