src/Web/AspNetCoreTemplate.Web/Controllers/UsersDataController.cs
namespace AspNetCoreTemplate.Web.Controllers
{
    using System.IO;
    using System.Threading.Tasks;

    using AspNetCoreTemplate.Common;
    using AspNetCoreTemplate.Services.Data.Addresses;
    using AspNetCoreTemplate.Services.Data.Courier;
    using AspNetCoreTemplate.Services.Data.Restaurant;
    using AspNetCoreTemplate.Services.Data.Users;
    using AspNetCoreTemplate.Web.ViewModels.Couriers;
    using AspNetCoreTemplate.Web.ViewModels.LocationObjects;
    using AspNetCoreTemplate.Web.ViewModels.Restaurants;
    using AspNetCoreTemplate.Web.ViewModels.Users;
    using AspNetCoreTemplate.Web.ViewModels.UsersData;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;

    public class UsersDataController : Controller
    {
        private readonly IUserService userService;
        private readonly IUsersDataService usersDataService;
        private readonly IDocumentsService documentsService;
        private readonly IImagesService imagesService;
        private readonly IWebHostEnvironment hostEnvironment;
        private readonly ICourierService courierService;
        private readonly ICitiesService citiesService;
        private readonly IRestaurantService restaurantService;

        public UsersDataController(
            IUserService userService,
            IUsersDataService usersDataService,
            IDocumentsService documentsService,
            IImagesService imagesService,
            IWebHostEnvironment hostEnvironment,
            ICourierService courierService,
            ICitiesService citiesService,
            IRestaurantService restaurantService)
        {
            this.userService = userService;
            this.usersDataService = usersDataService;
            this.documentsService = documentsService;
            this.imagesService = imagesService;
            this.hostEnvironment = hostEnvironment;
            this.courierService = courierService;
            this.citiesService = citiesService;
            this.restaurantService = restaurantService;
        }

        [Authorize]
        public IActionResult NavBar()
        {
            return this.View();
        }

        [Authorize]
        public IActionResult AllDocuments()
        {
            var viewModel = new IndexDetailsViewModel();
            var documents = this.documentsService.GetAllDocuments<DocumentDetails>();
            viewModel.Documents = (System.Collections.Generic.ICollection<DocumentDetails>)documents;
            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult Index(string name, string id, string userName, string userDataId)
        {
            if (id != null)
            {
                userName = this.userService.GetById<UserIndexView>(id).UserName;
                name = this.usersDataService.GetName(id);
                userDataId = this.usersDataService.GetId(id);
            }
            else if (userDataId != null)
            {
                id = this.usersDataService.GetByDataId(userDataId);
                userName = this.userService.GetById<UserIndexView>(id).UserName;
                name = this.usersDataService.GetName(id);
            }
            else
            {
                if (id == null && name == null && userName == null)
                {
                    userName = this.User.Identity.Name.ToString();
                    id = this.userService.GetUserName(userName);
                    name = this.usersDataService.GetName(id);
                    userDataId = this.usersDataService.GetId(id);
                }
                else
                {
                    userName = this.User.Identity.Name.ToString();
                    id = this.userService.GetUserName(userName);
                    userDataId = this.usersDataService.GetId(id);
                }
            }

            var documents = this.documentsService.GetAllDocumentsByUser<DocumentDetails>(userDataId);
            var viewModel = new IndexDetailsViewModel();
            viewModel.Name = name;
            viewModel.UserId = id;
            viewModel.UserName = userName;
            viewModel.Documents = (System.Collections.Generic.ICollection<DocumentDetails>)documents;

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult IndexPdf(string name, string id, string userName)
        {
            var userDataid = string.Empty;

            if (id == null && name == null && userName == null)
            {
                userName = this.User.Identity.Name.ToString();
                id = this.userService.GetUserName(userName);
                name = this.usersDataService.GetName(id);
                userDataid = this.usersDataService.GetId(id);
            }
            else
            {
                userName = this.User.Identity.Name.ToString();
                id = this.userService.GetUserName(userName);
                userDataid = this.usersDataService.GetId(id);
            }

            var documents = this.documentsService.GetAllDocumentsByUser<DocumentDetails>(userDataid);
            var viewModel = new IndexDetailsViewModel();
            viewModel.Name = name;
            viewModel.UserId = id;
            viewModel.UserName = userName;
            viewModel.Documents = (System.Collections.Generic.ICollection<DocumentDetails>)documents;

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult Create()
        {
            var userName = this.User.Identity.Name.ToString();
            var id = this.userService.GetUserName(userName);
            var userData = this.usersDataService.GetByUserId<UserDataIndexViewModel>(id);
            var name = string.Empty;

            var viewModel = new CreateUserDataViewModel();
            if (name != null)
            {
                viewModel.Messages = string.Format(GlobalConstants.MessageUserDataController, name);
            }

            viewModel.UserUserName = userName;
            viewModel.UserId = id;

            return this.View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateUserDataViewModel input)
        {
            var name = input.Name;
            var userName = this.User.Identity.Name.ToString();
            var id = this.userService.GetUserName(userName);

            var data = await this.usersDataService.CreateAsyncUserData(input.Name, id);
            this.TempData["InfoMessageAreas"] = "Data was created!";
            if (this.User.IsInRole(GlobalConstants.AdminRoleName) || this.User.IsInRole(GlobalConstants.AdministratorRoleName) ||
                this.User.IsInRole(GlobalConstants.RestaurantRoleName) || this.User.IsInRole(GlobalConstants.CourierRoleName))
            {
                return this.RedirectToAction(nameof(this.Index), new { @name = input.Name });
            }
            else
            {
                return this.RedirectToAction("Index", "Home");
            }
        }

        [Authorize]
        public IActionResult Uploaud(string id)
        {
            var viewModel = new UploadDocumentViewModel();
            if (id != null)
            {
                var userDataId = this.usersDataService.GetByUserId<UserDataIndexViewModel>(id);
                viewModel.UserDataId = userDataId.Id;
            }

            return this.View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Uploaud1(IFormFile files, UploadDocumentViewModel input)
        {
            if (input.UserDataId == null)
            {
                var userName = this.User.Identity.Name.ToString();
                var id = this.userService.GetUserName(userName);
                input.UserDataId = this.usersDataService.GetId(id);
            }

            if (files != null)
            {
                if (files.Length > 0)
                {
                    var newName = files.FileName;
                    var indexOf = newName.IndexOf('.');
                    var exstention = newName.Substring(indexOf + 1);
                    var target = new MemoryStream();

                    using (target)
                    {
                        files.CopyTo(target);
                    }

                    var objfiles = await this.documentsService.CreateAsyncDocument(newName, exstention, target.ToArray(), input.UserDataId);
                }
            }

            var userId = this.usersDataService.GetByDataId(input.UserDataId);

            return this.RedirectToAction(nameof(this.Index), new { id = userId });
        }

        public IActionResult ViewDocument(string id)
        {
            var document = this.documentsService.GetByIdDelete<DocumentDetails>(id);
            var target = new MemoryStream(document.DataFiles);
            var pdfDocument = new FileStreamResult(target, "application/pdf");
            return pdfDocument;
        }

        [Authorize]
        public IActionResult IndexPdfOne(string id)
        {
            var viewModel = new UserDocumentPdfDetail();
            var document = this.documentsService.GetByIdDelete<DocumentDetails>(id);
            var userDocument = document.UserData;
            var realName = userDocument.Name;
            var userId = this.usersDataService.GetByDataId(document.UserDataId);

            viewModel.Name = document.Name;
            viewModel.Id = id;
            viewModel.FileType = document.FileType;
            viewModel.DataFiles = document.DataFiles;
            viewModel.CreatedOn = document.CreatedOn;
            viewModel.RaelName = realName;
            viewModel.UserDataId = userId;

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult Download(string id)
        {

src/Web/AspNetCoreTemplate.Web/Views/UsersData/AllCouriers.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using AspNetCoreTemplate.Web.Resources
@inject LocService SharedLocalizer
@inject IViewLocalizer Localizer
@using AspNetCoreTemplate.Common
@model AspNetCoreTemplate.Web.ViewModels.UsersData.AllUserDataCourierViewModel

@{
    this.ViewData["Title"] = $"All Couriers";

}
@if (this.TempData["InfoMessageApply"] != null)
{
    <div class="alert alert-success">
        @this.TempData["InfoMessageApply"]
    </div>
}

<div class="text-center">
    <h1 style="margin:20px;">@this.ViewData["Title"]</h1>
</div>
@if (Model.Couriers.Count() == 0)
{

}
else
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>@SharedLocalizer.GetLocalizedHtmlString("Name")</th>
                <th>@SharedLocalizer.GetLocalizedHtmlString("City")</th>
                <th>@SharedLocalizer.GetLocalizedHtmlString("Area")</th>
                <th>@SharedLocalizer.GetLocalizedHtmlString("MobilePhone")</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var courier in Model.Couriers)
            {
                <tr>
                    <td>@courier.Name </td>
                    <td>@courier.CityName</td>
                    <td>@courier.Area.AreaName</td>
                    <td>@courier.Phone</td>
                    <td><a class="btn btn-primary" asp-area="" asp-controller="Courier" asp-action="Details" asp-route-id="@courier.Id">@SharedLocalizer.GetLocalizedHtmlString("Details")</a></td>

                </tr>
            }
        </tbody>
    </table>
}

@if (this.User.IsInRole(GlobalConstants.AdminRoleName) ||
this.User.IsInRole(GlobalConstants.AdministratorRoleName))
{
<a class="btn btn-primary userDataInfo2" asp-area="" asp-controller="Users" asp-action="NavBarAdmin">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>
}
else
{
<a class="btn btn-primary userDataInfo2" asp-area="" asp-controller="Home" asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>
}

src/Web/AspNetCoreTemplate.Web/Views/UsersData/AllDocuments.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using AspNetCoreTemplate.Web.Resources
@inject LocService SharedLocalizer
@inject IViewLocalizer Localizer
@using AspNetCoreTemplate.Common
@model AspNetCoreTemplate.Web.ViewModels.UsersData.IndexDetailsViewModel

@{
    this.ViewData["Title"] = "Information about all Documents";
    var documents = this.Model.Documents;
}

<div class="text-center">
    <h1 class="display-4">@this.ViewData["Title"]</h1>
</div>


@if (Model.Documents.Count() == 0)
{
    <h5>@SharedLocalizer.GetLocalizedHtmlString("NoDocumentIn")</h5>
}
else
{
    <div class="row userDataInfo">
        @foreach (var doc in Model.Documents)
        {
            <div class="media col-md-10">
                <div class="media-body">
                    <h5 class="mt-0">@doc.UserData.Name : <a asp-controller="UsersData" asp-action="IndexPdfOne" asp-route-id="@doc.Id">@doc.Name / @SharedLocalizer.GetLocalizedHtmlString("Create") - @doc.CreatedOn</a> <a class="btn btn-danger btn-delete" asp-controller="UsersData" asp-action="AskDelete" asp-route-id="@doc.Id">@SharedLocalizer.GetLocalizedHtmlString("Delete")</a></h5>
                </div>
            </div>

        }
    </div>
}

<div>
    <a class="btn btn-primary" asp-area="" asp-controller="UsersData" asp-action="NoActive" asp-route-id="@Model.UserId">@SharedLocalizer.GetLocalizedHtmlString("DeleteDocumentByThisUser")</a>
    <a class="btn btn-primary" asp-area="" asp-controller="UsersData" asp-action="Uploaud" asp-route-id="@Model.UserId">@SharedLocalizer.GetLocalizedHtmlString("UploudNewDocument")</a>
    <a class="btn btn-primary" asp-area="" asp-controller="UsersData" asp-action="NavBar">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>
</div>

src/Web/AspNetCoreTemplate.Web/Views/UsersData/AllRestaurants.cshtml
@using AspNetCoreTemplate.Common
@using Microsoft.AspNetCore.Mvc.Localization
@using AspNetCoreTemplate.Web.Resources
@inject LocService SharedLocalizer
@inject IViewLocalizer Localizer
@model AspNetCoreTemplate.Web.ViewModels.UsersData.AllUserDataReastaurantViewModel

@{
    this.ViewData["Title"] = $"All Reastaurants";

}
@if (this.TempData["InfoMessageApply"] != null)
{
    <div class="alert alert-success">
        @this.TempData["InfoMessageApply"]
    </div>
}

<div class="text-center">
    <h1 style="margin:20px;">@this.ViewData["Title"]</h1>
</div>
@if (Model.Restaurants.Count() == 0)
{

}
else
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>@SharedLocalizer.GetLocalizedHtmlString("Name")</th>
                <th>@SharedLocalizer.GetLocalizedHtmlString("City")</th>
                <th>@SharedLocalizer.GetLocalizedHtmlString("Area")</th>
                <th>@SharedLocalizer.GetLocalizedHtmlString("MobilePhone")</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var reastaurant in Model.Restaurants)
            {
                <tr>
                    <td>@reastaurant.Name </td>
                    <td>@reastaurant.CityName</td>
                    <td>@reastaurant.Area.AreaName</td>
                    <td>@reastaurant.Phone</td>
                    <td><a class="btn btn-primary" asp-area="" asp-controller="Restaurant" asp-action="Details" asp-route-id="@reastaurant.Id">@SharedLocalizer.GetLocalizedHtmlString("Details")</a></td>

                </tr>
            }
        </tbody>
    </table>
}

@if (this.User.IsInRole(GlobalConstants.AdminRoleName) ||
this.User.IsInRole(GlobalConstants.AdministratorRoleName))
{
<a class="btn btn-primary userDataInfo2" asp-area="" asp-controller="Users" asp-action="NavBarAdmin">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>
}
else
{
<a class="btn btn-primary userDataInfo2" asp-area="" asp-controller="Home" asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>
}

src/Web/AspNetCoreTemplate.Web/Views/UsersData/AllUsers.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using AspNetCoreTemplate.Web.Resources
@inject LocService SharedLocalizer
@inject IViewLocalizer Localizer
@using AspNetCoreTemplate.Common
@model AspNetCoreTemplate.Web.ViewModels.UsersData.AllUser

@{
    this.ViewData["Title"] = $"All Users";

}
@if (this.TempData["InfoMessageApply"] != null)
{
    <div class="alert alert-success">
        @this.TempData["InfoMessageApply"]
    </div>
}

<div class="text-center">
    <h1 style="margin:20px;">@this.ViewData["Title"]</h1>
</div>
@if (Model.Users.Count() == 0)
{

}
else
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>@SharedLocalizer.GetLocalizedHtmlString("Name")</th>
                <th>@SharedLocalizer.GetLocalizedHtmlString("Email")</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model.Users)
            {
                <tr>
                    <td>@user.UserName </td>
                    <td>@user.Email</td>
                    <td><a class="btn btn-primary" asp-area="" asp-controller="UsersData" asp-action="Details" asp-route-id="@user.Id">@SharedLocalizer.GetLocalizedHtmlString("Details")</a></td>

                </tr>
            }
        </tbody>
    </table>
}

@if (this.User.IsInRole(GlobalConstants.AdminRoleName) ||
this.User.IsInRole(GlobalConstants.AdministratorRoleName))
{
    <a class="btn btn-primary userDataInfo2" asp-area="" asp-controller="Users" asp-action="NavBarAdmin">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>
}
else
{
    <a class="btn btn-primary userDataInfo2" asp-area="" asp-controller="Home" asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>
}

src/Web/AspNetCoreTemplate.Web/Views/UsersData/AskDelete.cshtml
@using AspNetCoreTemplate.Common
@model AspNetCoreTemplate.Web.ViewModels.UsersData.DocumentDeleted

@{
    this.ViewData["Title"] = "UsersData";
}

<div class="text-center">
    <h1 class="display-4">@this.ViewData["Title"]</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

 <div class="row">
            <h3>Document Name @Model.Name</h3>
            <div class="media col-md-10">
                <div class="media-body">
                    <a class="btn btn-danger" asp-area="" asp-controller="UsersData" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                </div>
            </div>

    </div>

src/Web/AspNetCoreTemplate.Web/Views/UsersData/Create.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using AspNetCoreTemplate.Web.Resources
@inject LocService SharedLocalizer
@inject IViewLocalizer Localizer
@model AspNetCoreTemplate.Web.ViewModels.UsersData.CreateUserDataViewModel
@{
    this.ViewData["Title"] = "Create Info for User";
    var userName = Model.UserUserName;
    var id = Model.UserId;
}
@if (this.TempData["InfoMessageCity"] != null)
{
    <div class="alert alert-success">
        @this.TempData["InfoMessageCity"]
    </div>
}

<h1>@this.ViewData["Title"] @userName</h1>

<form method="post" asp-action="Create">
    <div class="media-body">
        <input type="hidden" asp-for="UserId" class="form-control" value="@id" />
        <input type="hidden" asp-for="UserUserName" class="form-control" value="@userName" />
    </div>
    <div>
        <p>@Model.Messages</p>
    </div>
    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control col-md-4" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <hr />
    <input type="submit" class="btn btn-primary" />
</form>

<a class="btn btn-primary userDataInfo2" asp-area="" asp-controller="UsersData" asp-action="NavBar">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>

src/Web/AspNetCoreTemplate.Web/Views/UsersData/Details.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using AspNetCoreTemplate.Web.Resources
@inject LocService SharedLocalizer
@inject IViewLocalizer Localizer
@model AspNetCoreTemplate.Web.ViewModels.LocationObjects.LocationObjectIndexViewModel
@{
    this.ViewData["Title"] = "Detail User";
}
@if (this.TempData["InfoMessageCourier"] != null)
{
    <div class="alert alert-success">
        @this.TempData["InfoMessageCourier"]
    </div>
}

<h1 style="margin:20px;">@this.ViewData["Title"]</h1>

<div class="container-fluid mt-100">
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-header">
                    <div class="media flex-wrap w-100 align-items-center">
                         <div class="media-body ml-3">
                            <div class="text-muted small">
                                <p>@SharedLocalizer.GetLocalizedHtmlString("FullName") - @Model.Name</p>
                            </div>
                            <div class="text-muted small">
                                <p>@SharedLocalizer.GetLocalizedHtmlString("MobilePhone") @Model.Info</p>
                            </div>
                            @*<div class="text-muted small">
                                <p>@SharedLocalizer.GetLocalizedHtmlString("Email") - @Model.User.Email</p>
                            </div>
                            <div class="text-muted small">
                                <p>@SharedLocalizer.GetLocalizedHtmlString("City") - @Model.Address.City.CityName</p>
                            </div>*@
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<a class="btn btn-primary userDataInfo2" asp-area="" asp-controller="Home" asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>

src/Web/AspNetCoreTemplate.Web/Views/UsersData/Image.cshtml
@model AspNetCoreTemplate.Web.ViewModels.UsersData.UploadImageViewModel
@{
    this.ViewData["Title"] = "Uploaud Data";
    var userDataid = Model.UserDataId;
}
<h1>Index</h1>
<div class="row">
    <div class="col-md-5">
        <form method="post" enctype="multipart/form-data" asp-controller="UsersData" asp-action="Image1">
            <div class="form-group">
                <div class="col-md-10">
                    <p>Upload file</p>
                    <input class="form-control" name="files" type="file" />
                </div>
            </div>
            <input type="hidden" asp-for="UserDataId" class="form-control" value="@userDataid" />
            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" class="btn btn-success" value="Upload" />
                </div>
            </div>
        </form>
    </div>
</div> 

src/Web/AspNetCoreTemplate.Web/Views/UsersData/Image2.cshtml
@model AspNetCoreTemplate.Web.ViewModels.UsersData.UploadImageViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@using AspNetCoreTemplate.Web.Resources
@inject LocService SharedLocalizer
@inject IViewLocalizer Localizer
@{
    this.ViewData["Title"] = "Uploaud Data";
    var userDataid = Model.UserDataId;
}
<h1>Index</h1>
<div class="row">
    <div class="col-md-5">
        <form method="post" enctype="multipart/form-data" asp-controller="UsersData" asp-action="Image3">
            <div class="form-group">
                <div class="col-md-10">
                    <p>@SharedLocalizer.GetLocalizedHtmlString("UploudFile")</p>
                    <input class="form-control" name="files" type="file" />
                </div>
            </div>
            <input type="hidden" asp-for="UserDataId" class="form-control" value="@userDataid" />
            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" class="btn btn-success" value="Upload" />
                </div>
            </div>
        </form>
    </div>
</div> 

src/Web/AspNetCoreTemplate.Web/Views/UsersData/Index.cshtml
@using AspNetCoreTemplate.Common
@model AspNetCoreTemplate.Web.ViewModels.UsersData.IndexDetailsViewModel

@{
    this.ViewData["Title"] = "Information about all Documents";
    var documents = this.Model.Documents;
}

<div class="text-center">
    <h1 class="display-4">@this.ViewData["Title"]</h1>
</div>

<h1>Full Name @Model.Name</h1>
<h3>UserName @Model.UserName</h3>

@if (Model.Documents.Count() == 0)
{
<h5>No Document in @Model.Name</h5>
}
else
{
<div class="row userDataInfo">
    @foreach (var doc in Model.Documents)
    {
    <div class="media col-md-10">
        <div class="media-body">
            <h5 class="mt-0"><a asp-controller="UsersData" asp-action="IndexPdfOne" asp-route-id="@doc.Id">@doc.Name / Created - @doc.CreatedOn</a> <a class="btn btn-danger btn-delete" asp-controller="UsersData" asp-action="AskDelete" asp-route-id="@doc.Id">Delete</a></h5>
        </div>
    </div>
        
    }
</div>
}

<div>
    <a class="btn btn-primary" asp-area="" asp-controller="UsersData" asp-action="NoActive" asp-route-id="@Model.UserId">Delete document By this User</a>
    <a class="btn btn-primary" asp-area="" asp-controller="UsersData" asp-action="Uploaud" asp-route-id="@Model.UserId">Uploud new Document</a>
    <a class="btn btn-primary" asp-area="" asp-controller="UsersData" asp-action="NavBar">Back</a>
</div>

src/Web/AspNetCoreTemplate.Web/Views/UsersData/NavBar.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using AspNetCoreTemplate.Web.Resources
@inject LocService SharedLocalizer
@inject IViewLocalizer Localizer
@using AspNetCoreTemplate.Common
@using AspNetCoreTemplate.Data.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    this.ViewData["Title"] = "Users Panel";
}
<ul>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="UsersData" asp-action="Create">@SharedLocalizer.GetLocalizedHtmlString("Create")</a>
    </li>
    @if (this.User.IsInRole(GlobalConstants.RestaurantRoleName) ||
  this.User.IsInRole(GlobalConstants.CourierRoleName) ||
  this.User.IsInRole(GlobalConstants.AdminRoleName) ||
  this.User.IsInRole(GlobalConstants.AdministratorRoleName))
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="UsersData" asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("Info")</a>
        </li>

    }
    @if (this.User.IsInRole(GlobalConstants.AdminRoleName) ||
      this.User.IsInRole(GlobalConstants.AdministratorRoleName))
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="UsersData" asp-action="AllDocuments">@SharedLocalizer.GetLocalizedHtmlString("All")</a>
        </li>
    }
</ul>

<a class="btn btn-primary" asp-area="" asp-controller="Home" asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("Back")</a>

src/Web/AspNetCoreTemplate.Web/Views/UsersData/ViewDocument.cshtml
@using AspNetCoreTemplate.Common
@model AspNetCoreTemplate.Web.ViewModels.UsersData.DocumentDetails

@{
    this.ViewData["Title"] = "UsersData";
}

<h1>@Model.DataFiles</h1>